export const ADD_COUNT_MUTATION = 'ADD_COUNT_MUTATION';
export const CHANGE_LOAD_SHOW_STATE = 'CHANGE_LOAD_SHOW_STATE';
export const OPERATION_RESULT_SHOW = 'OPERATION_RESULT_SHOW';
export const OPERATION_RESULT_HIDDEN = 'OPERATION_RESULT_HIDDEN';
export const CHANE_STATE_USERID = 'CHANE_STATE_USERID';
export const CHANE_STATE_USER = 'CHANE_STATE_USER';
